### ISSUE TITLE
bin/cake not executable after deploy

### ISSUE THREAD

**Issue by steefaan** [jadb/capcake#17]
Hey @jadb, unfortunately the `bin/cake` file isn't an executable after deploy. This will trigger an error if I do `deploy:migrations:migrate` dierectly after `deploy`.

```
/usr/bin/env: bin/cake
Permission denied
```

**Comment by jadb** [comment]
Hmm, never encountered this issue before. Not sure how to best replicate it, any ideas/suggestions?

**Comment by steefaan** [comment]
I could solve this issue. If you change the permissions of `bin/cake` on your local system and push the changes to github you will receive the correct permissions when you pull from github. Maybe it's still a good idea to change the permissions with capistrano to cover this issue.

**Comment by jadb** [comment]
I am closing this as I tried replicating over and over but no success.

As long as `bin/cake` permissions are correctly set in the repo (doesn't matter about local), the server will be able to run it.
